// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Models.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<string>("AppName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlawString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastBuild")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MitigationWebhookId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MitigationWebhookId");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("DataAccess.Models.MitigationWebhook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Demand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastFired")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecondsBetweenCheck")
                        .HasColumnType("int");

                    b.Property<string>("SendAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimesFired")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WebHooks");
                });

            modelBuilder.Entity("DataAccess.Models.PropertyCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExpectedValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MitigationWebhookId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MitigationWebhookId");

                    b.ToTable("Conditons");
                });

            modelBuilder.Entity("DataAccess.Models.WebhookLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageSent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusReturned")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeFired")
                        .HasColumnType("datetime2");

                    b.Property<string>("WebHookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebHookSendAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DataAccess.Models.App", b =>
                {
                    b.HasOne("DataAccess.Models.MitigationWebhook", "MitigationWebhook")
                        .WithMany("Apps")
                        .HasForeignKey("MitigationWebhookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Models.PropertyCondition", b =>
                {
                    b.HasOne("DataAccess.Models.MitigationWebhook", "MitigationWebhook")
                        .WithMany("PropertyConditions")
                        .HasForeignKey("MitigationWebhookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
